### ISSUE TITLE
Pass incremental value in associative array

### ISSUE THREAD

**Issue by bceyssens** [Tracardi/tracardi-key-counter#1]
Hi @atompie,

Is it possible to also add the option to pass incremental values in an associative array on the event?
https://github.com/Tracardi/tracardi-key-counter/blob/54f4c0cffc9e482e6d2065be8e34d3089589597c/tracardi_key_counter/service/key_counter.py#L11

Example track event:
```
window.tracker.track("event-type", {"keys": {
  "key1": 3,
  "key2": 1
}});
```

Config on key counter action:
```
{
  "key": "event@properties.keys",
  "save_in": "profile@stats.counters"
}
```
This would result in:
```
profile@stats.counters.key1: *original value* + 3
profile@stats.counters.key2: *original value* + 1
```

**Comment by atompie** [comment]
@bceyssens This a good idea and easy to implement.
